# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

# This file has been adapted from the template.

name: CI/CD (Quality & Test)

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    strategy:
      # プロジェクトが要求するPython 3.12のみでテストを実行
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5 # バージョンを v5 に固定

      # ★ 修正箇所1: Poetryのインストールを、Pythonのセットアップの直前に移動します
      - name: Install Poetry
        uses: snok/install-poetry@v1 # 最も安定したPoetryインストーラーを使用

      - name: Set up Python ${{ matrix.python-version }}
        # 修正箇所2: cache機能を動作させるため、PythonセットアップをPoetryインストール後に移動
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry" # Poetryの依存関係をキャッシュ
          
      # 依存関係のインストール (devグループを含む)
      - name: Install dependencies (with dev)
        # 依存関係を解決し、インストール（プロジェクト自体はインストールしない）
        run: poetry install --with dev --no-root

      # プロジェクト本体を仮想環境にインストール
      - name: Install project root
        run: poetry install --only-root

      # --- 品質チェック (Flake8を削除し、RuffとMypyに置き換え) ---

      # 1. スタイルと論理エラーのチェック (Ruff)
      - name: Run Ruff Linter Check
        run: poetry run ruff check src tests

      # 2. 型チェック (Mypy)
      - name: Run Mypy Type Check
        # pyproject.tomlに設定したignore rules (googleapiclient)が適用されます
        run: poetry run mypy src

      # 3. ユニットテストの実行 (Pytest)
      - name: Run Pytest
        run: poetry run pytest
