name: CI/CD (Test & Lint)

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test_and_lint:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: "3.12"

    steps:
      # リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v5

      # Python環境のセットアップ
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # PoetryのインストールとPATH設定を確実に実行します。
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.1

      # 依存関係のインストール (devグループを含む)
      - name: Install dependencies
        run: poetry install --with dev --no-root

      # パッケージを編集可能モードでインストール
      - name: Install package root
        # --only-root は pyproject.toml で定義されたプロジェクト自体をインストール
        run: poetry install --only-root

      # --- 静的解析と品質チェック ---

      - name: Run Ruff Linter Check
        run: poetry run ruff check src tests

      - name: Run Mypy Type Check
        run: poetry run mypy src

      - name: Run Pytest
        run: poetry run pytest
